### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by N6WT** [Pari030/GetIpByAnydesk#2]
When I run py main.py I get  File "C:\Users\Kent\GetIpByAnydesk\src\main.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Pari030** [comment]
You should install requests library with ```py -m pip install requests``` or ```python3 -m pip install requests``` for Linux

**Comment by N6WT** [comment]
Thanks, that did the trick. I'm still kind of a nube.
